name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby: ['2.2', '2.3', '2.4', '2.5', '2.6', '2.7']
        rails: ['4.2', '4.2.api', '5.0', '5.1', '5.2']
        exclude:
          - ruby: '2.7'
            rails: '4.2'
          - ruby: '2.7'
            rails: '4.2.api'
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 1
        bundler-cache: true
    - name: Start MySQL and create DB
      run: |
        sudo systemctl start mysql.service
        mysql -uroot -proot -e 'create database marginalia_test;'
    - name: Start PostgresQL and create DB
      run: |
        sudo sed -i s/md5/trust/g /etc/postgresql/*/main/pg_hba.conf
        sudo systemctl start postgresql.service
        sudo -u postgres createuser --createdb --superuser ${USER}
        createdb typed_store_test
        echo "POSTGRES_URL=postgres://localhost/marginalia_test" >> $GITHUB_ENV
    - name: Tests
      run: bundle exec rake db:reset test:all
